### ISSUE TITLE
Ingest multijson format data from local file/blob container to a "NEW TABLE" in ADX always Fails

### ISSUE THREAD

**Issue by docast** [MicrosoftDocs/dataexplorer-docs#549]
Ingesting a JSON file with ( multijson) format always fails when ingested from local file/blob container to a NEW TABLE through "Ingest New data" option. 

when a multijson file is used to ingest into ADX cluster with "create new table" option, we see that the table schema gets created however, the data ingestion always fails with below error: 

BadRequest_InvalidBlob:BadRequest_EmptyBlob

This is because the UI, doesn't expose flexibility to chose "json/multijson" formats and because of which the ingestion always fails while ingesting a multijson file. The error is seen when imported from a local file/file from blob container. The issue occurs only when you create a new table as part of the Ingest new data option and you try to ingest a multijson file like below:

For example: the below simplest sample json is picked from:
https://docs.microsoft.com/en-us/azure/data-explorer/ingest-json-formats?tabs=kusto-query-language
If you try to create a new table as part of "Ingest New Data" UI one click ingestion option, the error can be easily reproduced. 

{
    "timestamp": "2019-05-02 15:23:50.0369439",
    "deviceId": "2945c8aa-f13e-4c48-4473-b81440bb5ca2",
    "messageId": "7f316225-839a-4593-92b5-1812949279b3",
    "temperature": 31.0301639051317,
    "humidity": 62.0791099602725
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16e646a2-3caa-02ac-3472-ee95c715b33e
* Version Independent ID: 78d8cd0e-ed42-0b08-5e01-f7bf8cce868e
* Content: [Use one-click ingestion to ingest JSON data from a local file to an existing table in Azure Data Explorer](https://docs.microsoft.com/en-us/azure/data-explorer/one-click-ingestion-existing-table)
* Content Source: [data-explorer/one-click-ingestion-existing-table.md](https://github.com/MicrosoftDocs/dataexplorer-docs/blob/master/data-explorer/one-click-ingestion-existing-table.md)
* Service: **data-explorer**
* GitHub Login: @orspod
* Microsoft Alias: **orspodek**

**Comment by SaurabhSharma-MSFT** [comment]
@docast Thanks for your feedback! We will investigate and update as appropriate.

**Comment by YaelSchuster** [comment]
@kerend @TzviaGT

**Comment by ArielYehezkely** [comment]
Hi @docast, 

Thanks for notifying. I've fixed the issue so the ingestion won't fail, it will be available next week. 
Having both Json and Multijson is confusing so we'll keep the UI as is and the file format you'll need to choose will be Json, under the hood we'll ingest the file as multijson.

**Comment by YaelSchuster** [comment]
Thanks @ArielYehezkely for your help.
@docast since the underlying issue has been fixed, I will proceed to close this issue. If you have further questions or comments, please feel free to reach out.

#please-close

**Comment by docast** [comment]
Hi Team, this is still broken:

I tried to ingest a new valid multiline Json into ADX using "Ingest new data". Now, its reporting "Stream_NoDataToIngest: The input stream produced 0 bytes. This usually means that the input JSON stream was ill formed." .

Previously I used to get "BadRequest_InvalidBlob:BadRequest_EmptyBlob". This is when I create a new table through UI "Ingest New data" option and try ingesting a multijson file.

However, whenever I ingest the row using ".ingest into table" with "Multiline" json, the ingestion is working: Json is valid, that's why .ingest option is working.


[cid:image001.jpg@01D6F044.39BBA710]

This is the json content:
{
              "ID": 100,
              "SourceComponent": "Parser",
              "LogTimeStamp": "2015-12-31 23:59:59.9",
              "SubComponent": "ParserScript",
              "Operation": "Starting:MLCParse_readBlobstorage",
              "LogInfo": "Read the Raw file from BlobStorage"
}


Regards,
Don Rohan Castelino

**Comment by orspod** [comment]
@ArielYehezkely - please assist

**Comment by ArielYehezkely** [comment]
Hi @docast,

You're right the fix hasn't been deployed yet. It will be available in version 1.0.11, which hopefully will be deployed during this week.
To check version go to Settings:
![image](https://user-images.githubusercontent.com/37837385/105628805-d1c57600-5e47-11eb-8d4d-edd902a778ec.png)
